### ISSUE TITLE
Erreur période de vacance scolaire à Clermont-Ferrand 

### ISSUE THREAD

**Issue by montaignec** [tataille/node-red-french-holidays#13]
Bonjour, 
Je vous fait remonter une difficulté ou un petit bug nous somme le vendredi 23/02/2024 en période de vacance scolaire à Clermont -Ferrand depuis lundi dernier.

Avec les paramètres  
- Academic Région : Clermont-Ferrand  
- Région: Métropole 
-
Le Noeud envoie L'objet  suivant :

day: 5
isPublicHoliday: false
isTomorrowPublicHoliday: false
publicHolidayName: null
nextPublicHolidayName: "Lundi de Pâques"
nextPublicHolidayDate: "01/04/2024"
isSchoolHolidays: false    <-------------------------Cela devrait être "true"
isTomorrowSchoolHolidays: false  <-------------------------Cela devrait être "true"
schoolHolidaysName: null
nextSchoolHolidaysCoutdownInDays: 50
nextSchoolHolidaysName: "Vacances de Printemps"
nextSchoolHolidaysStartDate: "13/04/2024"
nextSchoolHolidaysEndDate: "29/04/2024"
schoolPeriod: "2023-2024"
year: 2024

Merci pour votre travail, votre nœud est top ,
Cordialement,

**Comment by tataille** [comment]
What version?

Le ven. 23 févr. 2024, 8:39 AM, montaignec ***@***.***> a
écrit :

**Comment by tataille** [comment]
I double checked with version 1.1.9 and here is the result:

```json
{
 "day":5,
 "isPublicHoliday":false,
 "isTomorrowPublicHoliday":false,
 "publicHolidayName":null,
 "nextPublicHolidayName":"Lundi de Pâques",
 "nextPublicHolidayDate":"01/04/2024",
 "isSchoolHolidays":true,
 "isTomorrowSchoolHolidays":true,
 "schoolHolidaysName":"Vacances d'Hiver",
 "nextSchoolHolidaysCoutdownInDays":49,
 "nextSchoolHolidaysName":"Vacances de Printemps",
 "nextSchoolHolidaysStartDate":"12/04/2024",
 "nextSchoolHolidaysEndDate":"28/04/2024",
 "schoolPeriod":"2023-2024","year":2024
}
````

I tried with version 1.1.8 and I reproduce your issue, I recommend you to upgrade to version 1.2.1 (latest with extra fields)
see https://nodered.org/docs/user-guide/runtime/adding-nodes

**Comment by montaignec** [comment]
La version utilisé est la : 1.1.8 

je ne peux pas mettre à jour votre Nœud car Node-Red fait référence à ce site web: 
https://flows.nodered.org/node/@tataille/node-red-french-holidays

**Comment by tataille** [comment]
Yes that is correct. I recommand you to connect to your node red instance and delete the flow (node-red-french-holidays) then reinstall it (version 1.2.1)

**Comment by tataille** [comment]
What version of nodered do you run?
I tested with latest one 3.1.5 and update works like a charm. I suspect that you are running an old one.

![node-update](https://github.com/tataille/node-red-french-holidays/assets/20125208/19a1f464-6d2c-4464-8bc1-ca9a40fa79ca)

**Comment by tataille** [comment]
Fixed in version 1.2.1. Please update

**Comment by montaignec** [comment]
Merci pour votre aide ! :-D

**Comment by tataille** [comment]
> Merci pour votre aide ! :-D

Thanks!
