### ISSUE TITLE
Node Error with Stopping Node Red

### ISSUE THREAD

**Issue by Apollon16** [tataille/node-red-french-holidays#3]
Good morning,
I have been using the French Holiday knot for several months. Everything was working fine except since the last node 1.1.4 update.
Regularly but randomly, the node fails Node Red which stops completely. I am attaching a screenshot of the error.
Are you aware of this problem? Are you working on an update to fix the problem?
I'm not bilingual so I hope the google translation will be good.

![image](https://user-images.githubusercontent.com/89293183/224414378-f9300020-7453-41a9-9047-d55a5627d129.png)

**Comment by tataille** [comment]
Not aware of it. I will have a look in the next days.

Le ven. 10 mars 2023, 8:54 PM, Apollon16 ***@***.***> a
écrit :

**Comment by tataille** [comment]
What is the version of the module? Did you update it recently?

**Comment by Apollon16** [comment]
Node Red updated the module automatically to version 1.1.4 towards the end of January.

**Comment by tataille** [comment]
What are your parameters?
Academies?

Le ven. 10 mars 2023, 11:15 PM, Apollon16 ***@***.***> a
écrit :

**Comment by Apollon16** [comment]
The parameters are Academic Region: "versaille" and Region: "metropolis". Are there other parameters to enter? If so where do you find them?

**Comment by tataille** [comment]
No, it just to try to reproduce. What is the refresh frequency set in
nodered to retrieve the holidays?

Le ven. 10 mars 2023, 11:46 PM, Apollon16 ***@***.***> a
écrit :

**Comment by Apollon16** [comment]
I use the "timeswitch" module between "20:30 and 20:15" every day of the week.

**Comment by Apollon16** [comment]
I use the module to automatically vary the on and off time of my son's night light depending on the holidays or not.

**Comment by tataille** [comment]
Problem identified, Promise rejection cause node-red to stop. Working on a fix

**Comment by tataille** [comment]
@Apollon16 , could you please retry with version 1.1.5 and let me know

**Comment by Apollon16** [comment]
Hello, I just updated to version 1.1.5. Thank-you for your prompt response.

**Comment by tataille** [comment]
I will close the issue. If you find other problem, I will reopen
