### ISSUE TITLE
IsSchoolHoliday or IsSchoolHolidays

### ISSUE THREAD

**Issue by fdecourt** [tataille/node-red-french-holidays#6]
Hi,
I love this plugin, but
I can't find when the last update was made, but during the last few days, did you change the IsSchoolHoliday variable to IsSchoolHolidays (with an S) ?
THanks
Regards

**Comment by tataille** [comment]
Hi @fdecourt ,

Thanks for you comment.
The update was done on version 1.1.0
 https://github.com/tataille/node-red-french-holidays/releases/tag/1.1.0

Regards

**Comment by fdecourt** [comment]
OK, greats, thanks for the information.
Regards
