### ISSUE TITLE
Subflow problem

### ISSUE THREAD

**Issue by fdecourt** [tataille/node-red-french-holidays#7]
Hi,
I love your node, but I am facing an annoying problem.
I ma using the 1.1.6 version, on Nodered 16.0.2 in the latest version of HomeAssistant
When it is used in subflow, it won't return to the calling flow : 
![image](https://github.com/tataille/node-red-french-holidays/assets/4050977/53f3ffda-8cb2-4ced-baa7-2d916fdf97e0)
I am calling the first flow (number 1 - TEST_1).
You can see on the debug console, that Debug43 is called (number 2)
then I will have subflow Test debug
Then, I will see the Debug 39 (number 3), which is par of the other flow I didn't call.
So strangely, if I have your french holiday node in a subflow, it will jump to an other flow I didn't call.

The expected result should be to display the "Debug 37"

Here are the flows : 
`[{"id":"31453f98e1a076b4","type":"subflow","name":"test","info":"","category":"","in":[{"x":120,"y":300,"wires":[{"id":"954c766ad059f0cf"}]}],"out":[{"x":1220,"y":240,"wires":[{"id":"700798b947f75176","port":0}]},{"x":1300,"y":360,"wires":[{"id":"700798b947f75176","port":1}]}],"env":[],"meta":{},"color":"#DDAA99"},{"id":"700798b947f75176","type":"switch","z":"31453f98e1a076b4","name":"","property":"payload.isPublicHoliday","propertyType":"msg","rules":[{"t":"true"},{"t":"false"}],"checkall":"true","repair":false,"outputs":2,"x":980,"y":300,"wires":[["740278ebcf97a0da"],["711ab246c8a818fe"]]},{"id":"203e79540f27ef54","type":"debug","z":"31453f98e1a076b4","name":"debug 47","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":920,"y":180,"wires":[]},{"id":"740278ebcf97a0da","type":"debug","z":"31453f98e1a076b4","name":"debug 48","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":1140,"y":140,"wires":[]},{"id":"711ab246c8a818fe","type":"debug","z":"31453f98e1a076b4","name":"debug 49","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":1120,"y":460,"wires":[]},{"id":"954c766ad059f0cf","type":"french-holidays","z":"31453f98e1a076b4","name":"Rouen","academy":"Normandie","geo":"Métropole","x":590,"y":300,"wires":[["203e79540f27ef54","700798b947f75176"]]},{"id":"258d1f2643c8d4f6","type":"debug","z":"b673acb4e124a481","name":"debug 36","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":1140,"y":280,"wires":[]},{"id":"4e269c18350f4895","type":"debug","z":"b673acb4e124a481","name":"debug 37","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":1140,"y":340,"wires":[]},{"id":"3e4a79010abfb4ae","type":"debug","z":"b673acb4e124a481","name":"debug 38","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":1140,"y":420,"wires":[]},{"id":"214e66d947a79916","type":"debug","z":"b673acb4e124a481","name":"debug 39","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":1140,"y":480,"wires":[]},{"id":"959d9fe3ea241915","type":"debug","z":"b673acb4e124a481","name":"debug 43","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":1140,"y":220,"wires":[]},{"id":"e73013a76d654750","type":"debug","z":"b673acb4e124a481","name":"debug 44","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":1140,"y":540,"wires":[]},{"id":"bffacaa438356ddb","type":"subflow:31453f98e1a076b4","z":"b673acb4e124a481","name":"","x":790,"y":320,"wires":[["258d1f2643c8d4f6"],["4e269c18350f4895"]]},{"id":"c605279029daa972","type":"subflow:31453f98e1a076b4","z":"b673acb4e124a481","name":"","x":790,"y":460,"wires":[["3e4a79010abfb4ae"],["214e66d947a79916"]]},{"id":"9883d609a1f8e98d","type":"inject","z":"b673acb4e124a481","name":"TEST_2","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":440,"y":460,"wires":[["c605279029daa972","e73013a76d654750"]]},{"id":"259d36b3c93365e2","type":"inject","z":"b673acb4e124a481","name":"TEST_1","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"","payloadType":"date","x":420,"y":320,"wires":[["bffacaa438356ddb","959d9fe3ea241915"]]}]`

And the subflow : 

`[{"id":"700798b947f75176","type":"switch","z":"31453f98e1a076b4","name":"","property":"payload.isPublicHoliday","propertyType":"msg","rules":[{"t":"true"},{"t":"false"}],"checkall":"true","repair":false,"outputs":2,"x":980,"y":300,"wires":[["740278ebcf97a0da"],["711ab246c8a818fe"]]},{"id":"203e79540f27ef54","type":"debug","z":"31453f98e1a076b4","name":"debug 47","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":920,"y":180,"wires":[]},{"id":"740278ebcf97a0da","type":"debug","z":"31453f98e1a076b4","name":"debug 48","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":1140,"y":140,"wires":[]},{"id":"711ab246c8a818fe","type":"debug","z":"31453f98e1a076b4","name":"debug 49","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","statusVal":"","statusType":"auto","x":1120,"y":460,"wires":[]},{"id":"954c766ad059f0cf","type":"french-holidays","z":"31453f98e1a076b4","name":"Nantes","academy":"Nantes","geo":"Métropole","x":600,"y":300,"wires":[["203e79540f27ef54","700798b947f75176"]]}]`

I only face this problem with your node !

Thanks for your help

**Comment by tataille** [comment]
Hi @fdecourt , I'm checking...

**Comment by tataille** [comment]
Issue Found, it will be fixed in version 1.1.7

**Comment by tataille** [comment]
@fdecourt , don't hesitate to let me know when you can test version 1.1.7, and if ok, we will close the issue.

**Comment by fdecourt** [comment]
I will test it between today and tomorrow.
I used a workaround, by runing every morning a flow and insterting the result in a global variable.
I will rebuild what I had before.

**Comment by fdecourt** [comment]
Hi, it seems to be working well 
Thanks

**Comment by fdecourt** [comment]
Hi, it seems to be working well
Thanks
